
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * @author Arunima Mittra
 * Net ID: AXM170025
 * Course: CS 2336.502 
           Dr. Khan
 */
public class calculatorMain extends javax.swing.JFrame {
    String answerStr;
    String equationStr;
    boolean replace; //replaces or adds digits to number
    
    /**
     * Creates new form calculatorMain
     */
    public calculatorMain() {
        answerStr = "0";
        initComponents();
        answer.setText(answerStr);
        mathFull.setText(null);
        replace = true;
        
        answer.setEditable(false);
        mathFull.setEditable(false);
        
        hexNum.setText(answerStr);
        binNum.setText(answerStr);
        decNum.setText(answerStr);
        octNum.setText(answerStr);
        
    }
    
    private void setAnswer(String num) {
        if(answerStr.equals("0")) {
                replace = true;
            }
        
        if (replace) {
        answerStr = num; 
        replace = false;    }
        else {
        answerStr += num; }
        
        answer.setText(answerStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        div = new javax.swing.JButton();
        xor = new javax.swing.JButton();
        not = new javax.swing.JButton();
        and = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        period = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        add = new javax.swing.JButton();
        lsh = new javax.swing.JButton();
        rsh = new javax.swing.JButton();
        or = new javax.swing.JButton();
        leftBrace = new javax.swing.JButton();
        rightBrace = new javax.swing.JButton();
        negate = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        one = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        four = new javax.swing.JButton();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        second = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        titleProgrammer = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        decRadio = new javax.swing.JRadioButton();
        hexRadio = new javax.swing.JRadioButton();
        octRadio = new javax.swing.JRadioButton();
        binRadio = new javax.swing.JRadioButton();
        menuKey = new javax.swing.JLabel();
        ms = new javax.swing.JButton();
        m = new javax.swing.JButton();
        numPad = new javax.swing.JButton();
        binPad = new javax.swing.JButton();
        toggle = new javax.swing.JButton();
        decNum = new javax.swing.JTextField();
        hexNum = new javax.swing.JTextField();
        binNum = new javax.swing.JTextField();
        octNum = new javax.swing.JTextField();
        mathFull = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        setLocationByPlatform(true);
        setName("mainFrame"); // NOI18N
        setResizable(false);

        five.setBackground(new java.awt.Color(255, 255, 255));
        five.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        five.setText("5");
        five.setBorder(null);
        buttonGroup1.add(five);
        five.setMargin(new java.awt.Insets(2, 2, 2, 2));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(255, 255, 255));
        six.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        six.setText("6");
        six.setBorder(null);
        buttonGroup1.add(six);
        six.setMargin(new java.awt.Insets(2, 2, 2, 2));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        sub.setBackground(new java.awt.Color(245, 245, 245));
        sub.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        sub.setText("-");
        sub.setBorder(null);
        sub.setMargin(new java.awt.Insets(2, 2, 2, 2));

        eight.setBackground(new java.awt.Color(255, 255, 255));
        eight.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        eight.setText("8");
        eight.setBorder(null);
        buttonGroup1.add(eight);
        eight.setMargin(new java.awt.Insets(2, 2, 2, 2));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(255, 255, 255));
        nine.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nine.setText("9");
        nine.setBorder(null);
        buttonGroup1.add(nine);
        nine.setMargin(new java.awt.Insets(2, 2, 2, 2));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        mult.setBackground(new java.awt.Color(245, 245, 245));
        mult.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        mult.setText("*");
        mult.setBorder(null);
        mult.setMargin(new java.awt.Insets(2, 2, 2, 2));

        clear.setBackground(new java.awt.Color(245, 245, 245));
        clear.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        clear.setText("C");
        clear.setBorder(null);
        clear.setMargin(new java.awt.Insets(2, 2, 2, 2));

        backspace.setBackground(new java.awt.Color(245, 245, 245));
        backspace.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        backspace.setText("<x");
        backspace.setBorder(null);
        backspace.setMargin(new java.awt.Insets(2, 2, 2, 2));
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(245, 245, 245));
        div.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        div.setText("/");
        div.setBorder(null);
        div.setMargin(new java.awt.Insets(2, 2, 2, 2));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        xor.setBackground(new java.awt.Color(245, 245, 245));
        xor.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        xor.setText("Xor");
        xor.setBorder(null);
        xor.setEnabled(false);
        xor.setMargin(new java.awt.Insets(2, 2, 2, 2));
        xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xorActionPerformed(evt);
            }
        });

        not.setBackground(new java.awt.Color(245, 245, 245));
        not.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        not.setText("Not");
        not.setBorder(null);
        not.setEnabled(false);
        not.setMargin(new java.awt.Insets(2, 2, 2, 2));
        not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notActionPerformed(evt);
            }
        });

        and.setBackground(new java.awt.Color(245, 245, 245));
        and.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        and.setText("And");
        and.setBorder(null);
        and.setEnabled(false);
        and.setMargin(new java.awt.Insets(2, 2, 2, 2));
        and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(255, 255, 255));
        zero.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        zero.setText("0");
        zero.setBorder(null);
        buttonGroup1.add(zero);
        zero.setMargin(new java.awt.Insets(2, 2, 2, 2));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        period.setBackground(new java.awt.Color(245, 245, 245));
        period.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        period.setText(".");
        period.setBorder(null);
        period.setMargin(new java.awt.Insets(2, 2, 2, 2));
        period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(245, 245, 245));
        equal.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        equal.setText("=");
        equal.setBorder(null);
        equal.setMargin(new java.awt.Insets(2, 2, 2, 2));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        two.setText("2");
        two.setBorder(null);
        buttonGroup1.add(two);
        two.setMargin(new java.awt.Insets(2, 2, 2, 2));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        three.setText("3");
        three.setBorder(null);
        buttonGroup1.add(three);
        three.setMargin(new java.awt.Insets(2, 2, 2, 2));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(245, 245, 245));
        add.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        add.setText("+");
        add.setBorder(null);
        add.setMargin(new java.awt.Insets(2, 2, 2, 2));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        lsh.setBackground(new java.awt.Color(245, 245, 245));
        lsh.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lsh.setText("Lsh");
        lsh.setBorder(null);
        lsh.setEnabled(false);
        lsh.setMargin(new java.awt.Insets(2, 2, 2, 2));
        lsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lshActionPerformed(evt);
            }
        });

        rsh.setBackground(new java.awt.Color(245, 245, 245));
        rsh.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        rsh.setText("Rsh");
        rsh.setBorder(null);
        rsh.setEnabled(false);
        rsh.setMargin(new java.awt.Insets(2, 2, 2, 2));
        rsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rshActionPerformed(evt);
            }
        });

        or.setBackground(new java.awt.Color(245, 245, 245));
        or.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        or.setText("Or");
        or.setBorder(null);
        or.setEnabled(false);
        or.setMargin(new java.awt.Insets(2, 2, 2, 2));

        leftBrace.setBackground(new java.awt.Color(245, 245, 245));
        leftBrace.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        leftBrace.setText("(");
        leftBrace.setBorder(null);
        leftBrace.setMargin(new java.awt.Insets(2, 2, 2, 2));

        rightBrace.setBackground(new java.awt.Color(245, 245, 245));
        rightBrace.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        rightBrace.setText(")");
        rightBrace.setBorder(null);
        rightBrace.setMargin(new java.awt.Insets(2, 2, 2, 2));
        rightBrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBraceActionPerformed(evt);
            }
        });

        negate.setBackground(new java.awt.Color(245, 245, 245));
        negate.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        negate.setText("+/-");
        negate.setBorder(null);
        negate.setMargin(new java.awt.Insets(2, 2, 2, 2));

        e.setBackground(new java.awt.Color(255, 255, 255));
        e.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        e.setText("E");
        e.setBorder(null);
        buttonGroup2.add(e);
        e.setDefaultCapable(false);
        e.setMargin(new java.awt.Insets(2, 2, 2, 2));
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        f.setBackground(new java.awt.Color(255, 255, 255));
        f.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        f.setText("F");
        f.setBorder(null);
        buttonGroup2.add(f);
        f.setDefaultCapable(false);
        f.setMargin(new java.awt.Insets(2, 2, 2, 2));
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        one.setText("1");
        one.setBorder(null);
        buttonGroup1.add(one);
        one.setMargin(new java.awt.Insets(2, 2, 2, 2));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        c.setText("C");
        c.setBorder(null);
        buttonGroup2.add(c);
        c.setDefaultCapable(false);
        c.setMargin(new java.awt.Insets(2, 2, 2, 2));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        d.setBackground(new java.awt.Color(255, 255, 255));
        d.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        d.setText("D");
        d.setBorder(null);
        buttonGroup2.add(d);
        d.setDefaultCapable(false);
        d.setMargin(new java.awt.Insets(2, 2, 2, 2));
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        four.setText("4");
        four.setBorder(null);
        buttonGroup1.add(four);
        four.setMargin(new java.awt.Insets(2, 2, 2, 2));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        a.setText("A");
        a.setBorder(null);
        buttonGroup2.add(a);
        a.setDefaultCapable(false);
        a.setMargin(new java.awt.Insets(2, 2, 2, 2));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        b.setText("B");
        b.setToolTipText("");
        b.setBorder(null);
        buttonGroup2.add(b);
        b.setDefaultCapable(false);
        b.setMargin(new java.awt.Insets(2, 2, 2, 2));
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(255, 255, 255));
        seven.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        seven.setText("7");
        seven.setBorder(null);
        buttonGroup1.add(seven);
        seven.setMargin(new java.awt.Insets(2, 2, 2, 2));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        second.setBackground(new java.awt.Color(245, 245, 245));
        second.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        second.setText("2nd");
        second.setBorder(null);
        second.setMargin(new java.awt.Insets(2, 2, 2, 2));

        mod.setBackground(new java.awt.Color(245, 245, 245));
        mod.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        mod.setText("Mod");
        mod.setBorder(null);
        mod.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        ce.setBackground(new java.awt.Color(245, 245, 245));
        ce.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ce.setText("CE");
        ce.setBorder(null);
        ce.setMargin(new java.awt.Insets(2, 2, 2, 2));

        titleProgrammer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        titleProgrammer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleProgrammer.setText("Programmer");
        titleProgrammer.setPreferredSize(new java.awt.Dimension(60, 14));

        answer.setBackground(new java.awt.Color(240, 240, 240));
        answer.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        answer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        answer.setText("Value here");
        answer.setBorder(null);
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        buttonGroup3.add(decRadio);
        decRadio.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        decRadio.setText("DEC");
        decRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(hexRadio);
        hexRadio.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        hexRadio.setText("HEX");
        hexRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(octRadio);
        octRadio.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        octRadio.setText("OCT");
        octRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(binRadio);
        binRadio.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        binRadio.setText("BIN");
        binRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binRadioActionPerformed(evt);
            }
        });

        menuKey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-menu-30.png"))); // NOI18N
        menuKey.setAlignmentY(0.0F);
        menuKey.setEnabled(false);
        menuKey.setName("Menu"); // NOI18N
        menuKey.setRequestFocusEnabled(false);
        menuKey.setVerifyInputWhenFocusTarget(false);

        ms.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        ms.setText("MS");
        ms.setBorder(null);
        ms.setEnabled(false);
        ms.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });

        m.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        m.setText("M");
        m.setBorder(null);
        m.setEnabled(false);
        m.setMargin(new java.awt.Insets(2, 2, 2, 2));
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        numPad.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        numPad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-keypad-24.png"))); // NOI18N
        numPad.setBorder(null);
        numPad.setEnabled(false);
        numPad.setMargin(new java.awt.Insets(2, 2, 2, 2));
        numPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPadActionPerformed(evt);
            }
        });

        binPad.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        binPad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-data-24.png"))); // NOI18N
        binPad.setBorder(null);
        binPad.setEnabled(false);
        binPad.setMargin(new java.awt.Insets(2, 2, 2, 2));
        binPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binPadActionPerformed(evt);
            }
        });

        toggle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        toggle.setText("WORD");
        toggle.setBorder(null);
        toggle.setMargin(new java.awt.Insets(2, 2, 2, 2));

        decNum.setBackground(new java.awt.Color(240, 240, 240));
        decNum.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        decNum.setText("value here");
        decNum.setBorder(null);

        hexNum.setBackground(new java.awt.Color(240, 240, 240));
        hexNum.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        hexNum.setText("value here");
        hexNum.setBorder(null);

        binNum.setBackground(new java.awt.Color(240, 240, 240));
        binNum.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        binNum.setText("value here");
        binNum.setBorder(null);

        octNum.setBackground(new java.awt.Color(240, 240, 240));
        octNum.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        octNum.setText("value here");
        octNum.setBorder(null);
        octNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octNumActionPerformed(evt);
            }
        });

        mathFull.setBackground(new java.awt.Color(240, 240, 240));
        mathFull.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        mathFull.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mathFull.setText("value here");
        mathFull.setBorder(null);
        mathFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numPad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(binPad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toggle, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(leftBrace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rightBrace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(negate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lsh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rsh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(xor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(and, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(binRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(octRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(octNum, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(binNum)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(decRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(decNum))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(hexRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hexNum, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(menuKey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(titleProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(mathFull, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(answer))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(menuKey, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(titleProgrammer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(mathFull, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hexRadio)
                    .addComponent(hexNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decRadio)
                    .addComponent(decNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(octRadio)
                    .addComponent(octNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binRadio)
                    .addComponent(binNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numPad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(binPad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lsh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rsh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftBrace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightBrace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(and, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        hexRadio.getAccessibleContext().setAccessibleParent(hexNum);
        hexNum.getAccessibleContext().setAccessibleParent(hexNum);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        setAnswer("6");
    }//GEN-LAST:event_sixActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        setAnswer("9");

    }//GEN-LAST:event_nineActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        replace = true;
        if(answerStr.length() <= 1) {
            setAnswer("0");
        }
        else {
            setAnswer(answerStr.substring(0, answerStr.length() - 1));
        }
        
    }//GEN-LAST:event_backspaceActionPerformed

    private void notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notActionPerformed

    private void periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodActionPerformed
        // TODO add your handling code here:
        setAnswer(".");
    }//GEN-LAST:event_periodActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        setAnswer("3");
    }//GEN-LAST:event_threeActionPerformed

    private void rshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rshActionPerformed

    private void rightBraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBraceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightBraceActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
        setAnswer("F");
    }//GEN-LAST:event_fActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
        setAnswer("D");

    }//GEN-LAST:event_dActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        setAnswer("B");
    }//GEN-LAST:event_bActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        setAnswer(mathFull.getText());
    }//GEN-LAST:event_equalActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        mathFull.setText(answerStr+"+");
    }//GEN-LAST:event_addActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divActionPerformed

    private void andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_andActionPerformed

    private void xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xorActionPerformed

    private void lshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lshActionPerformed

    private void decRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decRadioActionPerformed
        zero.setEnabled(true);
        one.setEnabled(true);
        two.setEnabled(true);
        three.setEnabled(true);
        four.setEnabled(true);
        five.setEnabled(true);
        six.setEnabled(true);
        seven.setEnabled(true);
        eight.setEnabled(true);
        nine.setEnabled(true);
        a.setEnabled(false);
        b.setEnabled(false);
        c.setEnabled(false);
        d.setEnabled(false);
        e.setEnabled(false);
        f.setEnabled(false);
    }//GEN-LAST:event_decRadioActionPerformed

    private void hexRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexRadioActionPerformed
        // TODO add your handling code here:
        zero.setEnabled(true);
        one.setEnabled(true);
        two.setEnabled(true);
        three.setEnabled(true);
        four.setEnabled(true);
        five.setEnabled(true);
        six.setEnabled(true);
        seven.setEnabled(true);
        eight.setEnabled(true);
        nine.setEnabled(true);
        a.setEnabled(true);
        b.setEnabled(true);
        c.setEnabled(true);
        d.setEnabled(true);
        e.setEnabled(true);
        f.setEnabled(true);
    }//GEN-LAST:event_hexRadioActionPerformed

    private void octRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octRadioActionPerformed
        // TODO add your handling code here:
        zero.setEnabled(true);
        one.setEnabled(true);
        two.setEnabled(true);
        three.setEnabled(true);
        four.setEnabled(true);
        five.setEnabled(true);
        six.setEnabled(true);
        seven.setEnabled(true);
        eight.setEnabled(false);
        nine.setEnabled(false);
        a.setEnabled(false);
        b.setEnabled(false);
        c.setEnabled(false);
        d.setEnabled(false);
        e.setEnabled(false);
        f.setEnabled(false);
    }//GEN-LAST:event_octRadioActionPerformed

    private void binRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binRadioActionPerformed
        // TODO add your handling code here:
        zero.setEnabled(true);
        one.setEnabled(true);
        two.setEnabled(false);
        three.setEnabled(false);
        four.setEnabled(false);
        five.setEnabled(false);
        six.setEnabled(false);
        seven.setEnabled(false);
        eight.setEnabled(false);
        nine.setEnabled(false);
        a.setEnabled(false);
        b.setEnabled(false);
        c.setEnabled(false);
        d.setEnabled(false);
        e.setEnabled(false);
        f.setEnabled(false);
        

    }//GEN-LAST:event_binRadioActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
        setAnswer("E");
    }//GEN-LAST:event_eActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void numPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPadActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void binPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binPadActionPerformed
        // TODO add your handling code here:
        binNum.setText(Integer.toString(Integer.parseInt(answer.getText()),2));
    }//GEN-LAST:event_binPadActionPerformed

    private void octNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octNumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_octNumActionPerformed

    private void mathFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathFullActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mathFullActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        setAnswer("A");
    }//GEN-LAST:event_aActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        setAnswer("7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        setAnswer("8");
    }//GEN-LAST:event_eightActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        setAnswer("C");
    }//GEN-LAST:event_cActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        setAnswer("4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        setAnswer("5");
    }//GEN-LAST:event_fiveActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        setAnswer("1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        setAnswer("2");
    }//GEN-LAST:event_twoActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        setAnswer("0");
    }//GEN-LAST:event_zeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(
        UIManager.getSystemLookAndFeelClassName());
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton add;
    private javax.swing.JButton and;
    private javax.swing.JTextField answer;
    private javax.swing.JButton b;
    private javax.swing.JButton backspace;
    private javax.swing.JTextField binNum;
    private javax.swing.JButton binPad;
    private javax.swing.JRadioButton binRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton c;
    private javax.swing.JButton ce;
    private javax.swing.JButton clear;
    private javax.swing.JButton d;
    private javax.swing.JTextField decNum;
    private javax.swing.JRadioButton decRadio;
    private javax.swing.JButton div;
    private javax.swing.JButton e;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton f;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JTextField hexNum;
    private javax.swing.JRadioButton hexRadio;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leftBrace;
    private javax.swing.JButton lsh;
    private javax.swing.JButton m;
    private javax.swing.JTextField mathFull;
    private javax.swing.JLabel menuKey;
    private javax.swing.JButton mod;
    private javax.swing.JButton ms;
    private javax.swing.JButton mult;
    private javax.swing.JButton negate;
    private javax.swing.JButton nine;
    private javax.swing.JButton not;
    private javax.swing.JButton numPad;
    private javax.swing.JTextField octNum;
    private javax.swing.JRadioButton octRadio;
    private javax.swing.JButton one;
    private javax.swing.JButton or;
    private javax.swing.JButton period;
    private javax.swing.JButton rightBrace;
    private javax.swing.JButton rsh;
    private javax.swing.JButton second;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton sub;
    private javax.swing.JButton three;
    private javax.swing.JLabel titleProgrammer;
    private javax.swing.JButton toggle;
    private javax.swing.JButton two;
    private javax.swing.JButton xor;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
